import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Head from './head'
import Footer from '@/components/footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body data-aos-easing="ease-in-out-sine" data-aos-delay="0"
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen`}
      >
        {children}
        {/* <!-- Scroll Top --> */}
        {/* <a href="#" id="scroll-top" className="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a> */}

        {/* <!-- Preloader --> */}
        {/* <div id="preloader"></div> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
